app:
  version: "v1.0.0"
  port: 8081
  image:
    repository: "ghcr.io/anotherdanger/user-service"
    tag: "latest"
  affinity:
    key: label
    value: app

service:
  type: "ClusterIP"
  port: 80
  targetPort: 8081
  grpcPort: 50052
  grpcTargetPort: 50052

resources:
  hpa:
    minReplicas: 1
    maxReplicas: 3
    cpu:
      utilization: 50
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"
    
pdb:
  minAvailable: 1

gateway:
  name: gateway

env:
  APP_SERVER_PORT: "8081"
  APP_INTERNAL_PORT: "9090"
  APP_AUTH_GRPC_HOST: "auth-service-svc.default.svc.cluster.local"
  APP_AUTH_GRPC_PORT: "50051"
  APP_INTERNAL_GRPC_HOST: "0.0.0.0"
  APP_INTERNAL_GRPC_PORT: "50052"
  APP_POSTGRES_HOST:
  APP_POSTGRES_PORT: "5432"
  APP_POSTGRES_USER:
  APP_POSTGRES_DB: "db_user_test"
  APP_POSTGRES_SCHEMA: "test"
  APP_KAFKA_HOST:
  APP_KAFKA_PORT: "9092"
  APP_OTEL_HOST:
  APP_OTEL_PORT: 4317
  APP_REDIS_HOST:
  APP_REDIS_PORT: 6379
