apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "chart.labels" . | indent 4}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Release.Name}}-app
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{.Values.service.targetPort }}

  - name: grpc-internal
    protocol: TCP
    port: {{ .Values.service.grpcPort }}
    targetPort: {{.Values.service.grpcTargetPort }}