apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{.Release.Name}}-virtual-svc
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "chart.labels" . | indent 4}}
spec:
  hosts:
  - '*'
  gateways:
    - istio-system/{{.Values.gateway.name}}
  http:
    - match:
        - uri:
            prefix: /v1/auth/user/login
        - uri:
            prefix: /v1/auth/user/register
        - uri:
            prefix: /user_v1.UserService
        - uri:
            prefix: /v1/auth/user/verify
        - uri:
            prefix: /v1/auth/user/resend-email
        - uri:
            prefix: /v1/auth/user/logout
      route:
        - destination:
            host: {{include "user-chart.vs.host" .}}
            subset: v1
          weight: 100


